modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="minecraft_earth_mod"
version="1.3.0.2"
displayName="Minecraft Earth Mod"
credits="DereC_"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minecraft-earth-mod"
logoFile="logo.png"
authors="DereC_"
description='''
Adds the unique and cool features from Minecraft Earth to normal Minecraft!
'''


[[dependencies.minecraft_earth_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"


